[2024-12-23 11:00:42,514] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T10:50:00+00:00 [queued]>
[2024-12-23 11:00:42,642] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T10:50:00+00:00 [queued]>
[2024-12-23 11:00:42,646] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-23 11:00:42,646] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2024-12-23 11:00:42,647] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-23 11:00:42,991] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): warsaw_data_update_dag_script> on 2024-12-23T10:50:00+00:00
[2024-12-23 11:00:43,118] {standard_task_runner.py:52} INFO - Started process 105 to run task
[2024-12-23 11:00:43,315] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'warsaw_data_update_dag', 'warsaw_data_update_dag_script', '2024-12-23T10:50:00+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/warsaw.py', '--cfg-path', '/tmp/tmp523l1szg', '--error-file', '/tmp/tmpb4d1_gyp']
[2024-12-23 11:00:43,348] {standard_task_runner.py:77} INFO - Job 11: Subtask warsaw_data_update_dag_script
[2024-12-23 11:00:45,042] {logging_mixin.py:104} INFO - Running <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T10:50:00+00:00 [running]> on host 21ac49de6db4
[2024-12-23 11:00:45,536] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=warsaw_data_update_dag
AIRFLOW_CTX_TASK_ID=warsaw_data_update_dag_script
AIRFLOW_CTX_EXECUTION_DATE=2024-12-23T10:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-23T10:50:00+00:00
[2024-12-23 11:00:45,539] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-23 11:00:45,540] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts/ && python warsawUpdate.py']
[2024-12-23 11:00:45,649] {subprocess.py:75} INFO - Output:
[2024-12-23 11:00:49,050] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:00:49,051] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:00:49,051] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:00:49,051] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:00:49,051] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:00:49,051] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:00:49,051] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:00:49,051] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:00:49,051] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 10:57:07', 'hour': '10:57:07', 'temperature': 12.86}
[2024-12-23 11:00:49,051] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 11:00:12', 'hour': '11:00:12', 'temperature': 4.79}
[2024-12-23 11:00:49,051] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 10:54:43', 'hour': '10:54:43', 'temperature': 6.88}
[2024-12-23 11:00:49,052] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 10:54:32', 'hour': '10:54:32', 'temperature': 3.43}
[2024-12-23 11:00:49,146] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-23 11:00:49,654] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=warsaw_data_update_dag, task_id=warsaw_data_update_dag_script, execution_date=20241223T105000, start_date=20241223T110042, end_date=20241223T110049
[2024-12-23 11:00:49,802] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23 11:00:49,840] {local_task_job.py:151} INFO - Task exited with return code 0
