[2024-12-23 11:10:01,183] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T11:00:00+00:00 [queued]>
[2024-12-23 11:10:01,205] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T11:00:00+00:00 [queued]>
[2024-12-23 11:10:01,205] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-23 11:10:01,205] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2024-12-23 11:10:01,205] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-23 11:10:01,217] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): warsaw_data_update_dag_script> on 2024-12-23T11:00:00+00:00
[2024-12-23 11:10:01,227] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'warsaw_data_update_dag', 'warsaw_data_update_dag_script', '2024-12-23T11:00:00+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/warsaw.py', '--cfg-path', '/tmp/tmpjgsy4_vu', '--error-file', '/tmp/tmpkakz675p']
[2024-12-23 11:10:01,223] {standard_task_runner.py:52} INFO - Started process 547 to run task
[2024-12-23 11:10:01,228] {standard_task_runner.py:77} INFO - Job 12: Subtask warsaw_data_update_dag_script
[2024-12-23 11:10:01,322] {logging_mixin.py:104} INFO - Running <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T11:00:00+00:00 [running]> on host 21ac49de6db4
[2024-12-23 11:10:01,397] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=warsaw_data_update_dag
AIRFLOW_CTX_TASK_ID=warsaw_data_update_dag_script
AIRFLOW_CTX_EXECUTION_DATE=2024-12-23T11:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-23T11:00:00+00:00
[2024-12-23 11:10:01,400] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-23 11:10:01,401] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts/ && python warsawUpdate.py']
[2024-12-23 11:10:01,414] {subprocess.py:75} INFO - Output:
[2024-12-23 11:10:02,679] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:10:02,679] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:10:02,679] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:10:02,679] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:10:02,680] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:10:02,680] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:10:02,680] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:10:02,680] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:10:02,681] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 11:00:00', 'hour': '11:00:00', 'temperature': 6.88}
[2024-12-23 11:10:02,681] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 11:00:33', 'hour': '11:00:33', 'temperature': 3.3}
[2024-12-23 11:10:02,681] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 11:00:28', 'hour': '11:00:28', 'temperature': 12.9}
[2024-12-23 11:10:02,681] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 11:06:13', 'hour': '11:06:13', 'temperature': 4.97}
[2024-12-23 11:10:02,705] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-23 11:10:02,759] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=warsaw_data_update_dag, task_id=warsaw_data_update_dag_script, execution_date=20241223T110000, start_date=20241223T111001, end_date=20241223T111002
[2024-12-23 11:10:02,836] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23 11:10:02,867] {local_task_job.py:151} INFO - Task exited with return code 0
